import os
import django
import sys
from django.conf import settings

# Set up Django environment
sys.path.append('/home/mike/Desktop/singson-application/backend')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from core.models import User, Listing, Review

def run_test():
    print("Starting Review Feature Test...")

    # 1. Ensure we have a tenant and a listing
    tenant = User.objects.filter(is_landlord=False).first()
    if not tenant:
        print("No tenant user found. Please create one.")
        return

    listing = Listing.objects.first()
    if not listing:
        print("No listings found. Please create one.")
        return

    print(f"Using Tenant: {tenant.username}")
    print(f"Targeting Listing: {listing.title} (ID: {listing.id})")

    # 2. Delete existing reviews for this listing by this tenant to start fresh
    Review.objects.filter(reviewer=tenant, listing=listing).delete()
    print("Cleared previous reviews from this tenant for this listing.")

    # 3. Create a new 5-star review
    review = Review.objects.create(
        reviewer=tenant,
        listing=listing,
        rating=5,
        comment="This property is absolutely amazing! Test review generated by Antigravity."
    )
    print(f"Created Review: {review.rating} Stars - '{review.comment}'")

    # 4. Verify the Listing's computed properties update dynamically
    total_reviews = listing.reviews.count()
    print(f"Listing now has {total_reviews} total reviews.")
    average = float(sum(r.rating for r in listing.reviews.all()) / total_reviews) if total_reviews > 0 else 0
    print(f"New Average Rating: {average:.1f}")

    if total_reviews > 0 and average == 5.0:
        print("Backend test passed successfully! Head to the frontend to see it visually.")
    else:
        print("Test failed. Computed values do not match expected outcomes.")

if __name__ == '__main__':
    run_test()
