# Generated by Django 6.0.2 on 2026-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='house_rules',
            field=models.TextField(blank=True, default=''),
        ),
    ]
